### ISSUE TITLE
[Possible bug?] - Weather Stations not in FAA Data

### ISSUE THREAD

**Issue by Nikolai558** [KSanders7070/NASR_2_SCT#4]
Something caught my eye in the Weather Station Sector File that your program creates. 

Take a look at this image below. To the right you will see the FAA WXL.txt file open in txt editor. To the left you will see your .sct2 file that this program created. 

I am not sure exactly what's going on but if you look for (in this example) "CYDM", "CYTR", or "CZMT" in the FAA WXL.txt file, you won't find them. I don't know how many of these examples there are, these are just the ones that stuck out at me.  

![image](https://user-images.githubusercontent.com/38259407/99918910-59232b80-2cd7-11eb-8391-b37c6ae8c7f8.png)

**Comment by KSanders7070** [comment]
Fixed in 0.5.3-beta
https://github.com/KSanders7070/NASR_2_SCT/releases/tag/v0.5.3-beta
